version: '4.0'

actions:

  # Extract population for consort diagram

  generate_dataset_consort:
    run: ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition_consort.py --output output/dataset_consort.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_consort.csv.gz

  consort_diagram:
    run: python:v2 python analysis/preprocessing/consort_diagram.py
    needs: [generate_dataset_consort]
    outputs:
      highly_sensitive:
        dataset: output/consort_diagram_dta.csv


  # Extract population by WP
  
  #WP1
  generate_dataset_wp1:
    run: ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition_wp1.py --output output/tmp_dataset_wp1.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/tmp_dataset_wp1.csv.gz


  diabetes_algo_wp1:
    run: diabetes-algo:v0.0.6 --output output/dataset_wp1.csv.gz
    config:
      df_input: tmp_dataset_wp1.csv.gz
      birth_date: dob
      ethnicity_cat: ethnicity_cat
      df_output: dataset_wp1.csv.gz
    needs:
      - generate_dataset_wp1
    outputs:
      highly_sensitive:
        dataset: output/dataset_wp1.csv.gz

  #WP2_2
  generate_dataset_wp2_2:
    run: ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition_for_WP2_2.py --output output/tmp_dataset_wp2_2.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/tmp_dataset_wp2_2.csv.gz


  diabetes_algo_wp2_2:
    run: diabetes-algo:v0.0.6 --output output/dataset_wp2_2.csv.gz
    config:
      df_input: tmp_dataset_wp2_2.csv.gz
      birth_date: dob
      ethnicity_cat: ethnicity_cat
      df_output: dataset_wp2_2.csv.gz
    needs:
      - generate_dataset_wp2_2
    outputs:
      highly_sensitive:
        dataset: output/dataset_wp2_2.csv.gz

#WP2_2 with test
  generate_dataset_wp2_2t:
    run: ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition_for_WP2_2.py --output test/tmp_dataset_wp2_2t.csv.gz
    outputs:
      highly_sensitive:
        dataset: test/tmp_dataset_wp2_2t.csv.gz


  diabetes_algo_wp2_2t:
    run: diabetes-algo:v0.0.6 --output test/dataset_wp2_2t.csv.gz
    config:
      df_input: tmp_dataset_wp2_2t.csv.gz
      birth_date: dob
      ethnicity_cat: ethnicity_cat
      df_output: test/dataset_wp2_2t.csv.gz
    needs:
      - generate_dataset_wp2_2t
    outputs:
      highly_sensitive:
        dataset: test/dataset_wp2_2t.csv.gz


  #WP3
  generate_dataset_wp3:
    run: ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition_wp3.py --output output/tmp_dataset_wp3.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/tmp_dataset_wp3.csv.gz


  diabetes_algo_wp3:
    run: diabetes-algo:v0.0.6 --output output/dataset_wp3.csv.gz
    config:
      df_input: tmp_dataset_wp3.csv.gz
      birth_date: dob
      ethnicity_cat: ethnicity_cat
      df_output: dataset_wp3.csv.gz
    needs:
      - generate_dataset_wp3
    outputs:
      highly_sensitive:
        dataset: output/dataset_wp3.csv.gz
  
# etc...

# potential other actions to add:
  # create flow_chart (inclusions / exclusions);
  # quality assurance and other checks (e.g. checks for outliers, impossible values, weird distributions);
  # data processing steps for each work package (e.g. data manipulation to create new variables);
  # modelling;
  # creating output tables / figures;
  # etc.

