version: '4.0'

actions:

  # Extract population by WP
  
  generate_dataset_wp1:
    run: ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition_wp1.py --output output/dataset_wp1.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_wp1.csv.gz
  
  generate_dataset_wp2:
    run: ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition_wp2.py --output output/dataset_wp2.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_wp2.csv.gz
  
# etc...

# potential other actions to add:
  # create flow_chart (inclusions / exclusions);
  # quality assurance and other checks (e.g. checks for outliers, impossible values, weird distributions);
  # data processing steps for each work package (e.g. data manipulation to create new variables);
  # modelling;
  # creating output tables / figures;
  # etc.