version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz


  diabetes_algo_via_config:
    run: diabetes-algo:v0.0.6
    config:
      df_input: dataset.csv.gz
      birth_date: dob
      ethnicity_cat: ethnicity_cat
      df_output: data_processed.csv.gz

    needs:
      - generate_dataset

    outputs:
      highly_sensitive:
        dataset: output/data_processed.csv.gz
